
# Site
title: Hyeonsu Oh
bio: "Robot Enginner & AI Researcher"
description: "Moonrise is a fresh take on the classic Moon"
reading_time: true
words_per_minute: 200
logo: "assets/img/logo2.png"
background: "assets/img/location_img-44-698940471-148.jpg"
tiled_bg: false # Set this true if you want to tile your background image, otherwise it will be covered
locale: en_US
url: https://TolgaTatli.github.io/Moonrise

# Jekyll
permalink: /:title/
markdown: kramdown
highlighter: rouge
kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false
mathjax: true
sass:
  sass_dir: _sass
  style: compressed

# Comments

# Social
# if you don't have any of social below, comment the line.
#google:
# plus: username
#analytics:
#verify:
#ad-client:
#ad-slot:
#bing-verify:
#blog: https://blog.naver.com/hans324oh
email: hans324oh@gmail.com
#twitter: username
#facebook: username
github-url: ssapsu
#stackoverflow: 123456/username   from a "http://stackoverflow.com/users/123456/username" link
linkedin: 현수-오-3ab8ba2b8
#xing: username
instagram: gustn.__.324
#lastfm: username
#tumblr: username
#medium: '@username'
#pinterest: username
#foursquare: username
#steam: username
#dribbble: username
#youtube: username
youtube-channel: https://www.youtube.com/@%EC%98%A4%ED%98%84%EC%88%98-f7e
#soundcloud: username
#weibo: username
#flickr: username
#codepen: username
#keybase: username
#xmpp: username@server.com
#hackernews: username

# Plugins
plugins:
  - jekyll-mentions
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-include-cache

jekyll-mentions:
  base_url: https://github.com

# Exclude list
exclude:
  [
    README.md,
    Gemfile,
    Gemfile.lock,
    node_modules,
    gulpfile.js,
    package.json,
    _site,
    src,
    vendor,
    CNAME,
    LICENSE,
    Rakefile,
  ]
